### ISSUE TITLE
unless 的範例程式碼

### ISSUE THREAD

**Issue by ShikChen** [kaochenlong/learn-ruby-on-rails#11]
https://github.com/kaochenlong/learn-ruby-on-rails/blob/master/chapter05-ruby-basic-1.md#unless

覺得這邊的語意有點怪怪的...?

``` ruby
if not is_adult?(20)
  puts "你是大人了"
end
```

而且突然出現 `is_adult?` 這個函數，可能會令初學者感到困惑。
可能是當初編排章節的時候導致順序錯亂？因為這個函數的定義好像在[第七章](https://github.com/kaochenlong/learn-ruby-on-rails/blob/66cd6e83a60229fe20d892cf6ae82cee60363e49/chapter07-ruby-basic-3.md#問號跟驚嘆號也是方法的一部份)才出現。

**Comment by kaochenlong** [comment]
已在該段落加註說明
