### ISSUE TITLE
case when 範例程式碼行為不一致

### ISSUE THREAD

**Issue by ShikChen** [kaochenlong/learn-ruby-on-rails#12]
[第五章](https://github.com/kaochenlong/learn-ruby-on-rails/blob/master/chapter05-ruby-basic-1.md#如果太多的如果不然就if--else-)介紹**範圍技**的地方，從 `if age > 0 && age <= 3` 改成 `when 0..3` 在 `age = 0` 的時候行為不一致，看是要改成 `age >= 0` 還是 `when 1..3`。

**Comment by kaochenlong** [comment]
有的，這個後來已修正了，感謝提醒 :)
