### ISSUE TITLE
for..in 之使用

### ISSUE THREAD

**Issue by ShikChen** [kaochenlong/learn-ruby-on-rails#13]
在[第五章](https://github.com/kaochenlong/learn-ruby-on-rails/blob/master/chapter05-ruby-basic-1.md#迴圈及迭代loop-and-iteration)中提及

> 在 Ruby 的迴圈主要有幾種：
> 1. while 迴圈
> 2. times, upto, downto 方法
> 3. for..in 迴圈
> 4. 迭代（iteration）
> 在 Rails 的開發過程中，比較常用到的是第 3 種跟第 4 種，特別是第 4 種。

但以我的認知，很少看到且一般來說是不建議使用第三種語法的。
如 https://github.com/bbatsov/ruby-style-guide#no-for-loops
特別介紹這種語法有什麼特殊考量嗎？~除了對 python 人很友善以外~

**Comment by kaochenlong** [comment]
就是讓讀者知道其實 ruby 並不是只有 iteration 的 each 寫法而已(因為看過不少新手真的只知道有 each)
