### ISSUE TITLE
關於環境設定 - 安裝 Ruby / RVM 小節之編排

### ISSUE THREAD

**Issue by ShikChen** [kaochenlong/learn-ruby-on-rails#2]
從大綱看來，這系列文章主軸應當是 Rails；因此會嘗試跟著這篇文章安裝 Ruby 的人，可以合理的期望他們會想要跟著下 `gem install rails`。那此刻新手們可能會撞到下面這幾堵牆：

* 權限不夠
  * 跟著「Unix/Linux 作業系統」小節使用 `sudo` 以及系統套件管理程式安裝 ruby 的人
  * 跟著「Mac 作業系統」並發現自己已經有內建 Ruby 2.0 的人
  * 以上兩者在 `gem install` 的時候往往都需要 sudo 才能正常運作，並且新手不小心就會搞爛系統環境，未來可能會有靈異問題 XD
* 版本太舊
  * 跟著「Unix/Linux 作業系統」小節使用 `sudo` 以及系統套件管理程式安裝 ruby 的人，有可能會裝到太舊的 Ruby，如 Ubuntu 14.04 直接裝會是 Ruby 1.9.3
  * 跟著「Mac 作業系統」並發現自己已經有內建 Ruby 2.0 的人
  * 以上兩者的 Ruby 版本未達 Rails 5 的最低版本需求 Ruby 2.2

內文的撰寫方式較易讓新手認為 RVM 的安裝是非必需的，進而略過此步驟（這節相對來說又比較長與複雜）
> 如果各位跟我一樣都喜歡玩些新玩具，但又擔心環境被弄髒弄壞，推薦大家可以試試 RVM...

但實際上對新手來說安裝 RVM 可能比較不容易出問題？因為我自己平常是用 rbenv 所以不太確定 RVM 有可能會踩到什麼雷 XD

也許可以考慮改變措辭或編排方式，讓這系列文章對新手更友善😸

**Comment by kaochenlong** [comment]
感謝建議!

是的，使用系統內建的 ruby 常會需要用到 `sudo` 權限的問題而把系統弄爛了，但因為是 ruby 官網提到的安裝方法所以才稍微提一下。不過的確 ruby 官網只是教「怎麼裝 ruby」，而不是裝怎麼「裝給 rails 用的 ruby」，所以的確會有安裝到舊版 ruby 的問題。

事實上在上課的時候我都直接跳過系統 ruby 的安裝，直接使用 rvm 之類的工具。rvm 對新手來說會不會有雷呢? 當然有，而且還不少。不過因為作業系統 + Ruby 版本排列組合太多款，有的甚至還不只是單純作業系統問題。所以在上課時候踩到雷，大多就是下去一個一個幫同學們解。

所以在這篇的前面才提到，環境安裝，可能是整個 Rails 課程最難搞定的 :)
